name: Install Dependencies
description: Install dependencies using yarn

inputs:
  prod:
    type: boolean
    required: false
    default: false
  
runs:
  using: composite
  steps:
    - name: Set GitHub Packages Token
      shell: bash
      run: |
        npm config set @figurepos:registry https://npm.pkg.github.com/
        npm config set //npm.pkg.github.com/:_authToken ${{ github.token }}

    - name: Setup Node Cache
      id: node-cache
      uses: useblacksmith/cache@v5
      with:
        path: "**/node_modules"
        key: yarn-${{ runner.os }}-${{ inputs.prod == true && 'prod' || 'dev' }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('package.json') }}
        restore-keys:
          yarn-${{ runner.os }}-${{ inputs.prod == true && 'prod' || 'dev' }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('package.json') }}
          yarn-${{ runner.os }}-${{ inputs.prod == true && 'prod' || 'dev' }}-${{ hashFiles('yarn.lock') }}-
          yarn-${{ runner.os }}-${{ inputs.prod == true && 'prod' || 'dev' }}-
          yarn-${{ runner.os }}-

    - name: Install Dependencies
      shell: bash
      run: yarn install ${{ inputs.prod == true && '--prod' || '' }} --frozen-lockfile
      
