name: Install Dependencies
description: Install dependencies using yarn

inputs:
  prod:
    type: boolean
    required: false
    default: false
  token:
    description: "Auth token for the Figure Github npm registry"
    required: true

runs:
  using: composite
  steps:
    - name: Set GitHub packages token
      shell: bash
      run: |
        npm config set @figurepos:registry https://npm.pkg.github.com/
        npm config set //npm.pkg.github.com/:_authToken ${{ inputs.token }}

    - name: Setup node cache
      id: node-cache
      uses: actions/cache@v4
      with:
        path: "**/node_modules"
        key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('package.json') }}
        restore-keys:
          yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('package.json') }}
          yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-
          yarn-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: yarn install ${{ inputs.prod == true && '--prod' || '' }} --frozen-lockfile
