name: Node Test E2E
description: Runs the e2e tests for the Node.js app

inputs:
  docker-command:
    description: Command to start the service in Docker
    required: false
    type: string
    default: build/index.js
  ecr-repository-name:
    description: The ECR repository name
    required: true
  env-vars:
    description: Environment variables for the tests
    required: false
  npm-legacy-peer-deps:
    description: Whether to use legacy peer dependencies
    required: false
    default: false
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check if Tests Directory Exists
      id: check
      shell: bash
      run: |-
        if [[ ! -d "./tests" ]]; then
          echo "::warning title=Missing e2e tests::Tests directory not found, skipping e2e tests"
          echo "skip=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Set Environment Variables
      if: inputs.env-vars != ''
      shell: bash
      run: |
        echo "Setting environment variables"
        echo '${{ inputs.env-vars }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read -r line; do
          secret=${line#*=}
          echo "::add-mask::$secret"
          echo "$line" >> "$GITHUB_ENV"
          echo "- $line"
        done

    - name: Set Up Node.js
      if: steps.check.outputs.skip != 'true'
      uses: FigurePOS/github-actions/.github/actions/node-setup@v4

    - name: Install Dependencies
      if: steps.check.outputs.skip != 'true'
      uses: FigurePOS/github-actions/.github/actions/node-npm-install@v4
      with:
        legacy-peer-deps: ${{ inputs.npm-legacy-peer-deps }}

    - name: Load Docker Image
      if: steps.check.outputs.skip != 'true'
      uses: FigurePOS/github-actions/.github/actions/docker-load-image@v4
      with:
        service-name: ${{ inputs.service-name }}

    - name: Install Dependencies in Tests Directory
      if: steps.check.outputs.skip != 'true'
      uses: FigurePOS/github-actions/.github/actions/node-npm-install@v4
      with:
        directory: tests
        legacy-peer-deps: ${{ inputs.npm-legacy-peer-deps }}

    - name: Run Tests
      if: steps.check.outputs.skip != 'true'
      shell: bash
      run: |-
        sha_short=$(git rev-parse --short ${{ github.sha }})
        export SERVICE_DOCKER_IMAGE=637192944017.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.ecr-repository-name }}:$sha_short
        TEST_CMD="npm run start" npm run test:integration:prepare
      env:
        SERVICE_DOCKER_COMMAND: node --enable-source-maps ${{ inputs.docker-command }}
