name: Node Build
description: Builds the Node.js app and the docker image

inputs:
  additional-cache-path:
    description: Additional path to cache
    required: false
    default: ""
  ecr-repository-name:
    description: The ECR repository name
    required: true
  extra-apk-packages:
    description: Extra Alpine packages for Docker build (e.g. libjpeg-turbo libpng). Sets EXTRA_APK_PACKAGES build-arg.
    required: false
    default: ""
  npm-legacy-peer-deps:
    description: Whether to use legacy peer dependencies
    required: false
    default: "false"
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Up Node.js
      uses: FigurePOS/github-actions/.github/actions/node-setup@v5

    - name: Install Dev Dependencies
      uses: FigurePOS/github-actions/.github/actions/node-npm-install@v5
      with:
        additional-cache-path: ${{ inputs.additional-cache-path }}
        legacy-peer-deps: ${{ inputs.npm-legacy-peer-deps }}

    # SDK handling (for services that have a separate SDK directory)
    - name: Check for SDK Directory
      id: check-sdk
      shell: bash
      run: |
        if [ -d "./sdk" ] && [ -f "./sdk/package.json" ]; then
          echo "sdk-exists=true" >> $GITHUB_OUTPUT
          echo "SDK directory with package.json found. Will install dependencies."
        else
          echo "sdk-exists=false" >> $GITHUB_OUTPUT
          echo "No SDK directory with package.json found. Skipping SDK dependency installation."
        fi

    - name: Install SDK Dependencies
      if: steps.check-sdk.outputs.sdk-exists == 'true'
      uses: FigurePOS/github-actions/.github/actions/node-npm-install@v5
      with:
        directory: ./sdk
        legacy-peer-deps: ${{ inputs.npm-legacy-peer-deps }}

    - name: License Compliance
      shell: bash
      run: npm run check:licenses

    - name: Dependency Check
      shell: bash
      run: npm run check:deps

    # TypeScript build and prod dependencies are handled inside Docker
    - name: Resolve Dockerfile path
      id: dockerfile
      shell: bash
      run: |
        SHARED=./node_modules/@figurepos/platform-tooling/resources/service/Dockerfile
        if [ -f "$SHARED" ]; then
          echo "path=$SHARED" >> $GITHUB_OUTPUT
        else
          echo "path=" >> $GITHUB_OUTPUT
        fi
    - name: Build Image
      uses: FigurePOS/github-actions/.github/actions/docker-build-image@v5
      with:
        build-args: ${{ inputs.extra-apk-packages != '' && format('EXTRA_APK_PACKAGES={0}', inputs.extra-apk-packages) || '' }}
        file: ${{ steps.dockerfile.outputs.path }}
        repository-name: ${{ inputs.ecr-repository-name }}
        service-name: ${{ inputs.service-name }}
        
