name: Node Build
description: Builds the Node.js app and the docker image

inputs:
  additional-cache-path:
    description: Additional path to cache
    required: false
    default: ""
  buddy-trigger-url:
    description: The Buddy trigger URL
    required: true
  ecr-repository-name:
    description: The ECR repository name
    required: true
  npm-legacy-peer-deps:
    description: Whether to use legacy peer dependencies
    required: false
    default: true
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set Up Node.js
      uses: FigurePOS/github-actions/.github/actions/node-setup@v2
    
    - name: Install Dev Dependencies
      uses: FigurePOS/github-actions/.github/actions/node-npm-install@v2
      with:
        additional-cache-path: ${{ inputs.additional-cache-path }}
        legacy-peer-deps: ${{ inputs.npm-legacy-peer-deps }}

    - name: License Compliance
      shell: bash
      run: npm run check:licenses

    - name: Dependency Check
      shell: bash
      run: npm run check:deps

    - name: Build
      shell: bash
      run: npm run ci:build

    - name: Install Prod Dependencies
      uses: FigurePOS/github-actions/.github/actions/node-npm-install@v2
      with:
        additional-cache-path: ${{ inputs.additional-cache-path }}
        legacy-peer-deps: ${{ inputs.npm-legacy-peer-deps }}
        prod: true

    - name: Build Image
      uses: FigurePOS/github-actions/.github/actions/docker-build-image@v2
      with:
        repository-name: ${{ inputs.ecr-repository-name }}
        service-name: ${{ inputs.service-name }}

    - name: Send Slack Notification About Failure
      if: failure() && github.ref == 'refs/heads/master'
      uses: FigurePOS/github-actions/.github/actions/buddy-notify-fail-service@v2
      with:
        job-name: build
        service-name: ${{ inputs.service-name }}
        trigger-url: ${{ inputs.buddy-trigger-url }}

