name: Install Dependencies
description: Install dependencies using npm

inputs:
  additional-cache-path:
    description: Additional path to cache
    required: false
    default: ""
  directory:
    description: Directory to install dependencies in
    required: false
    default: "."
  legacy-peer-deps:
    description: Whether to use legacy peer dependencies
    required: false
    default: false
  prod:
    description: Whether to install only prod dependencies
    required: false
    default: false
  
runs:
  using: composite
  steps:
    - name: Set GitHub Packages Token
      shell: bash
      run: |
        npm config set //npm.pkg.github.com/:_authToken ${{ github.token }}

    - name: Setup Node Cache
      id: node-cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.directory }}/node_modules
          ${{ inputs.additional-cache-path }}
        key: npm-${{ runner.os }}-${{ inputs.prod == 'true' && 'prod' || 'dev' }}-${{ inputs.directory == '' && '.' || inputs.directory }}-${{ hashFiles(inputs.directory == '' && 'package-lock.json' || format('{0}/package-lock.json', inputs.directory)) }}

    - name: Install Dependencies
      shell: bash
      run: |
        echo "Running npm install"
        if [ "${{ inputs.directory }}" != "" ]; then
          cd "${{ inputs.directory }}"
          echo "Changing directory to ${PWD}"
        fi
        LEGACY_PEER_DEPS=""
        if [ "${{ inputs.legacy-peer-deps }}" = "true" ]; then
          echo "Using --legacy-peer-deps"
          LEGACY_PEER_DEPS="--legacy-peer-deps"
        fi
        PROD_FLAG=""
        if [ "${{ inputs.prod }}" = "true" ]; then
          echo "Using --production"
          PROD_FLAG="--production"
        fi
        npm install $PROD_FLAG $LEGACY_PEER_DEPS --no-fund
