name: Cleanup Authenticated Terraform Providers
description: Cleans up authenticated Terraform providers

inputs:
  aws-region:
    description: AWS region
    required: false
    type: string
    default: us-east-1
  providers:
    description: "Comma separated list of providers to authenticate"
    required: false
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - name: Assume AWS Role in Root Account Using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::637192944017:role/${{ inputs.service-name }}__oidc
        role-skip-session-tagging: true
    