name: Terraform Actions

inputs:
  aws-account-id:
    required: true
  aws-region:
    required: false
    default: us-east-1
  dir:
    required: false
    default: tf
  env:
    required: true
  github-token-terraform:
    required: false
  service-name:
    required: true

runs:
  using: composite
  steps:
    - name: Assume AWS Role in Root Account Using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::637192944017:role/${{ inputs.service-name }}__oidc
        role-skip-session-tagging: true
    
    - run: |
        DATADOG_API_KEY=$(aws ssm get-parameters --names "/terraform/datadog/api_key" --region="${{ inputs.aws-region }}" --query 'Parameters[].Value' --output text --with-decryption)
        echo "DATADOG_API_KEY=$DATADOG_API_KEY" >> "$GITHUB_ENV"

        DATADOG_APP_KEY=$(aws ssm get-parameters --names "/terraform/datadog/app_key" --region="${{ inputs.aws-region }}" --query 'Parameters[].Value' --output text --with-decryption)
        echo "DATADOG_APP_KEY=$DATADOG_APP_KEY" >> "$GITHUB_ENV"
      shell: bash

    - run: |
        if [ -n "${{ inputs.github-token-terraform }}" ]; then
          echo "Configuring GitHub token for Terraform"
          echo "machine github.com login username password ${{ inputs.github-token-terraform }}" > ~/.netrc
          git config --global url."https://github.com/".insteadOf "git://github.com/"
          git config --global advice.detachedHead false
        fi
      shell: bash
      
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7
    
    - run: |
        cd ${{ inputs.dir }}
        terraform init -reconfigure \
          -backend-config="bucket=fgr-terraform-state" \
          -backend-config="dynamodb_table=fgr-terraform-state-locks" \
          -backend-config="key=aws/app/${{ inputs.env }}/${{ inputs.service-name }}/infrastructure.tfstate" \
          -backend-config="region=${{ inputs.aws-region }}" \
          -lock-timeout=60s
      shell: bash
    
