name: Node Test Lambda Functions
description: Runs the linters and tests for the Node.js lambda functions

inputs:
  buddy-trigger-url:
    description: The Buddy trigger URL
    required: true
  directory:
    description: The directory containing the lambda functions
    required: false
    default: ./lambda
  npm-legacy-peer-deps:
    description: Whether to use legacy peer dependencies
    required: false
    default: false
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Up Node.js
      uses: FigurePOS/github-actions/.github/actions/node-setup@v3

    - name: Install Dependencies
      uses: FigurePOS/github-actions/.github/actions/node-npm-install@v3
      with:
        directory: ${{ inputs.directory }}
        legacy-peer-deps: ${{ inputs.npm-legacy-peer-deps }}

    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        
        # Check if package.json exists
        if [ ! -f "package.json" ]; then
          echo "::warning::No package.json found in ${{ inputs.directory }}"
          exit 0
        fi
        
        # Check if "ti" script exists
        has_ti_script=false
        if grep -q "\"ti\":" package.json; then
          has_ti_script=true
        fi
        
        # Check if "tip" script exists  
        has_tip_script=false
        if grep -q "\"tip\":" package.json; then
          has_tip_script=true
        fi
        
        # Run ti script if it exists
        if [ "$has_ti_script" = true ]; then
          echo "Running 'npm run ti' for ${{ inputs.directory }}"
          if ! npm run ti; then
            echo "::error::npm run ti failed in ${{ inputs.directory }}"
            exit 1
          fi
        else
          echo "::warning::Lambda function in ${{ inputs.directory }} does not have a 'ti' script defined in package.json"
        fi
        
        # Run tip script if it exists
        if [ "$has_tip_script" = true ]; then
          echo "Running 'npm run tip' for ${{ inputs.directory }}"
          if ! TEST_CMD="npm run ti" npm run tip; then
            echo "::error::npm run tip failed in ${{ inputs.directory }}"
            exit 1
          fi
        else
          echo "::warning::Lambda function in ${{ inputs.directory }} does not have a 'tip' script defined in package.json"
        fi

    - name: Send Slack Notification About Failure
      if: failure() && github.ref == 'refs/heads/master'
      uses: FigurePOS/github-actions/.github/actions/buddy-notify-fail-service@v3
      with:
        job-name: test-unit
        service-name: ${{ inputs.service-name }}
        trigger-url: ${{ inputs.buddy-trigger-url }}

