name: Node Test Lambda Functions
description: Runs the linters and tests for the Node.js lambda functions

inputs:
  aws-region:
    description: The AWS region
    required: false
    default: us-east-1
  buddy-trigger-url:
    description: The Buddy trigger URL
    required: true
  directory:
    description: The directory containing the lambda functions
    required: false
    default: ./lambda
  npm-legacy-peer-deps:
    description: Whether to use legacy peer dependencies
    required: false
    default: false
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Up Node.js
      uses: FigurePOS/github-actions/.github/actions/node-setup@v4

    - name: Assume AWS Role in Root Account Using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::637192944017:role/${{ inputs.service-name }}__oidc
        role-skip-session-tagging: true

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Install Dependencies
      uses: FigurePOS/github-actions/.github/actions/node-npm-install@v4
      with:
        directory: ${{ inputs.directory }}
        legacy-peer-deps: ${{ inputs.npm-legacy-peer-deps }}

    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        
        # Check if package.json exists
        if [ ! -f "package.json" ]; then
          echo "::warning::No package.json found in ${{ inputs.directory }}"
          exit 0
        fi
        
        # Check if "ti" script exists
        if ! grep -q "\"ti\":" package.json; then
          echo "::warning::No ti script found in ${{ inputs.directory }}"
          exit 0
        fi
        
        # Check if "tip" script exists  
        if ! grep -q "\"tip\":" package.json; then
          echo "::warning::No tip script found in ${{ inputs.directory }}"
          exit 0
        fi
        
        # Run tests
        if ! TEST_CMD="npm run ti" npm run tip; then
          echo "::error::npm run tip failed in ${{ inputs.directory }}"
          exit 1
        fi

    - name: Send Slack Notification About Failure
      if: failure() && github.ref == 'refs/heads/master'
      uses: FigurePOS/github-actions/.github/actions/buddy-notify-fail-service@v4
      with:
        job-name: test-unit
        service-name: ${{ inputs.service-name }}
        trigger-url: ${{ inputs.buddy-trigger-url }}

