name: Create GitHub Deployment (GitHub)
description: Create a GitHub Deployment for a given environment and ref
inputs:
  environment:
    description: Deployment environment (e.g., development, production)
    required: true
  ref:
    description: Git ref to deploy (commit SHA or ref)
    required: false
    default: ${{ github.sha }}
  description:
    description: Description for the deployment
    required: false
    default: Deploy
outputs:
  deployment-id:
    description: The created deployment ID
    value: ${{ steps.create.outputs.deployment-id }}
runs:
  using: composite
  steps:
    - name: Create Deployment
      id: create
      uses: actions/github-script@v7
      with:
        script: |
          const response = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `${{ inputs.ref }}`,
            environment: `${{ inputs.environment }}`,
            description: `${{ inputs.description }}`,
            required_contexts: []
          });
          core.setOutput('deployment-id', response.data.id);
    - name: Mark Deployment In Progress
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: ${{ steps.create.outputs.deployment-id }},
            state: 'in_progress',
            description: 'Deployment started'
          });
