name: Authenticate Terraform Providers
description: Authenticates Terraform providers

inputs:
  aws-region:
    description: AWS region
    required: false
    type: string
    default: us-east-1
  providers:
    description: "Comma separated list of providers to authenticate"
    required: false
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - name: Assume AWS Role in Root Account Using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::637192944017:role/${{ inputs.service-name }}__oidc
        role-skip-session-tagging: true
    - name: Set Variables From SSM
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        echo "Fetching SSM parameters..."
        PARAMS=$(aws ssm get-parameters-by-path \
          --path "/terraform/" \
          --recursive \
          --with-decryption \
          --region "$AWS_REGION" \
          --query 'Parameters[*].[Name,Value]' \
          --output text)

        while IFS=$'\t' read -r name value; do
          # Convert SSM path to environment variable name (lowercase)
          var_name=$(echo "$name" | sed 's|/terraform/||' | tr '/' '_')
          
          # Add TF_VAR_ prefix for Terraform variables
          var_name="TF_VAR_${var_name}"
          
          echo "Variable $var_name set."
          echo "::add-mask::$value"
          echo "$var_name=$value" >> "$GITHUB_ENV"
        done <<< "$PARAMS"
