name: Build Docker image and upload to artifacts
description: Builds a Docker image and uploads it to artifacts

inputs:
  aws-account-id:
    required: false
    default: 637192944017 # Root account
  aws-region:
    required: false
    default: us-east-1
  repository-name:
    required: true
  repository-url:
    required: false
    default: 637192944017.dkr.ecr.us-east-1.amazonaws.com
  service-name:
    required: true

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.service-name }}__oidc
        role-skip-session-tagging: true
    
    - id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - uses: useblacksmith/setup-docker-builder@v1
    
    - id: sha_short
      shell: bash
      run: echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

    - id: docker_file
      shell: bash
      run: echo "file_name=${{ inputs.service-name }}-${{ steps.sha_short.outputs.sha_short }}.tar" >> $GITHUB_OUTPUT

    - name: Create npmrc for BuildKit secret
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ github.token }}" > /tmp/npmrc
        echo "@figurepos:registry=https://npm.pkg.github.com/" >> /tmp/npmrc

    - name: Build Production Image
      uses: useblacksmith/build-push-action@v2
      with:
        context: .
        load: true
        target: production
        tags: ${{ inputs.repository-url }}/${{ inputs.repository-name }}:${{ steps.sha_short.outputs.sha_short }}
        outputs: type=docker,dest=/tmp/${{ steps.docker_file.outputs.file_name }}
        secret-files: |
          npmrc=/tmp/npmrc
    
    - uses: actions/upload-artifact@v4.1.0
      with:
        name: ${{ steps.docker_file.outputs.file_name }}
        path: "/tmp/${{ steps.docker_file.outputs.file_name }}"
