name: Docker Push
description: Pushes the docker image to the ECR repository

inputs:
  ecr-repository-name:
    description: The ECR repository name
    required: true
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Load docker image
      uses: FigurePOS/github-actions/.github/actions/docker-load-image@v4
      with:
        service-name: ${{ inputs.service-name }}

    - name: Push Docker Image
      uses: FigurePOS/github-actions/.github/actions/docker-push-image@v4
      with:
        repository-name: ${{ inputs.ecr-repository-name }}
        service-name: ${{ inputs.service-name }}
