name: Mobile Set Env
description: Creates the env.json file for the app from the input JSON

inputs:
  env_json:
    description: 'The JSON'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run white label config checks
      if: ${{ inputs.env_json }}
      shell: bash
      # We have to pass the input as environment variable to the script because it's a secret and GHA masks it
      run: 'echo "$ENV_JSON" > env.json'
      env:
        ENV_JSON: ${{ inputs.env_json }}

