name: Node Test Unit
description: Runs the linters and unit tests for the Node.js app

inputs:
  buddy-trigger-url:
    description: The Buddy trigger URL
    required: true
  env-vars:
    description: Environment variables for the tests
    required: false
  npm-legacy-peer-deps:
    description: Whether to use legacy peer dependencies
    required: false
    default: false
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Up Node.js
      uses: FigurePOS/github-actions/.github/actions/node-setup@v2

    - name: Install Dependencies
      uses: FigurePOS/github-actions/.github/actions/node-npm-install@v2
      with:
        legacy-peer-deps: ${{ inputs.npm-legacy-peer-deps }}

    - name: Set Environment Variables
      if: inputs.env-vars != ''
      shell: bash
      run: |
        echo '${{ inputs.env-vars }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read -r line; do
          secret=${line#*=}
          echo "::add-mask::$secret"
          echo "$line" >> "$GITHUB_ENV"
        done

    - name: Run Linters and Unit Tests
      shell: bash
      run: npm run ci:test

    - name: Send Slack Notification About Failure
      if: failure() && github.ref == 'refs/heads/master'
      uses: FigurePOS/github-actions/.github/actions/buddy-notify-fail-service@v2
      with:
        job-name: test-unit
        service-name: ${{ inputs.service-name }}
        trigger-url: ${{ inputs.buddy-trigger-url }}

