name: Terraform Validate
description: Validates the Terraform code

inputs:
  aws-account-id:
    description: AWS account ID
    required: false
    default: 880892332156 # Dev account
    type: string
  aws-region:
    description: AWS region
    required: false
    type: string
    default: us-east-1
  backend-s3-key:
    description: The S3 key for the backend
    required: false
    type: string
  buddy-trigger-url:
    description: The Buddy trigger URL
    required: true
  dir:
    required: false
    default: tf
  github-token-terraform:
    description: GitHub token to access other private repositories
    required: false
  service-name:
    description: The service name
    required: true
  

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform Init
      uses: FigurePOS/github-actions/.github/actions/terraform-init@v4
      with:
        aws-account-id: ${{ inputs.aws-account-id }}
        backend-s3-key: ${{ inputs.backend-s3-key }}
        dir: ${{ inputs.dir }}
        env: development
        github-token-terraform: ${{ inputs.github-token-terraform }}
        service-name: ${{ inputs.service-name }}
      env:
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Terraform Validate
      uses: FigurePOS/github-actions/.github/actions/terraform-validate@v4
      with:
        aws-account-id: ${{ inputs.aws-account-id }}
        dir: ${{ inputs.dir }}
        env: development
        service-name: ${{ inputs.service-name }}
      env:
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Misconfigurations Check
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: ${{ inputs.dir }}
        quiet: true
        framework: terraform
        output_format: cli
        skip_check: CKV_AWS_7,CKV_AWS_18,CKV_AWS_51,CKV_AWS_65,CKV_AWS_68,CKV_AWS_119,CKV_AWS_136,CKV_AWS_144,CKV_AWS_145,CKV_AWS_149,CKV_AWS_158,CKV_AWS_159,CKV_AWS_163,CKV_AWS_191,CKV_AWS_336,CKV_AWS_337,CKV_AWS_378,CKV2_AWS_34,CKV2_AWS_62,CKV_TF_1,CKV_TF_3
      env:
        GITHUB_PAT: ${{ inputs.github-token-terraform }}

    - name: Send Slack Notification About Failure
      if: failure() && github.ref == 'refs/heads/master'
      uses: FigurePOS/github-actions/.github/actions/buddy-notify-fail-service@v4
      with:
        job-name: terraform-validate
        service-name: ${{ inputs.service-name }}
        trigger-url: ${{ inputs.buddy-trigger-url }}

