name: Terraform Validate
description: Validates the Terraform code

inputs:
  aws-account-id:
    description: AWS account ID
    required: false
    default: 880892332156 # Dev account
  aws-region:
    description: AWS region
    required: false
    default: us-east-1
  backend-s3-key:
    description: The S3 key for the backend
    required: false
  dir:
    required: false
    default: tf
  github-token-terraform:
    description: GitHub token to access other private repositories
    required: false
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Terraform Init
      uses: FigurePOS/github-actions/.github/actions/terraform-init@v6
      with:
        aws-account-id: ${{ inputs.aws-account-id }}
        backend-s3-key: ${{ inputs.backend-s3-key }}
        dir: ${{ inputs.dir }}
        env: development
        github-token-terraform: ${{ inputs.github-token-terraform }}
        service-name: ${{ inputs.service-name }}
      env:
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: https://npm.pkg.github.com
        scope: "@figurepos"

    - name: Install fgr
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: npm install --global "@figurepos/platform-tooling@2.8.0"

    - name: Set up tflint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.61.0

    - name: Install Checkov
      shell: bash
      run: pipx install "checkov==3.3.20"

    - name: fgr tf lint
      shell: bash
      working-directory: ${{ inputs.dir }}
      env:
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        args=(tf lint development --quiet --service-name "${{ inputs.service-name }}" --region "${{ inputs.aws-region }}")
        if [ -n "${{ inputs.backend-s3-key }}" ]; then
          args+=(--backend-s3-key "${{ inputs.backend-s3-key }}")
        fi
        fgr "${args[@]}"
