name: Upload Source Maps to Bugsnag
description: Uploads source maps to Bugsnag

inputs:
  api-key:
    description: "Auth token for the Bugsnag API"
    required: true
  environment:
    description: "Environment to upload source maps for"
    required: true
    # options: development, production
  platform:
    description: "Platform to upload source maps for"
    required: true
    # options: ios, android, all
  version:
    description: "Version of the app"
    required: true
  code-bundle-suffix:
    description: "Allows to add custom suffix to bundle id for source maps upload"
    required: false
    default: ""
  working-directory:
    description: "Working directory"
    required: false

runs:
  using: composite
  steps:
    - name: Find Source Maps For iOS
      if: ${{ inputs.platform == 'ios' || inputs.platform == 'all' }}
      id: find-source-maps-ios
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Finding source maps for iOS..."
        bundle=$(find "dist/_expo/static/js/ios" -type f -iname "*.hbc")
        map=$(find "dist/_expo/static/js/ios" -type f -iname "*.map")
        echo "iOS bundle: $bundle"
        echo "iOS map: $map"
        echo "bundle=$bundle" >> $GITHUB_OUTPUT
        echo "map=$map" >> $GITHUB_OUTPUT

    - name: Upload Source Maps For iOS to Bugsnag
      if: ${{ inputs.platform == 'ios' || inputs.platform == 'all' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        code_bundle_id=${{ inputs.version }}-${{ inputs.environment }}
        if [ -n "${{ inputs.code-bundle-suffix }}" ]; then
          code_bundle_id="${code_bundle_id}-${{ inputs.code-bundle-suffix }}"
        fi
        npx bugsnag-source-maps upload-react-native \
          --api-key ${{ inputs.api-key }} \
          --code-bundle-id $code_bundle_id \
          --platform ios \
          --source-map ${{ steps.find-source-maps-ios.outputs.map }} \
          --bundle ${{ steps.find-source-maps-ios.outputs.bundle }}

    - name: Find Source Maps For Android
      if: ${{ inputs.platform == 'android' || inputs.platform == 'all' }}
      id: find-source-maps-android
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Finding source maps for Android..."
        bundle=$(find "dist/_expo/static/js/android" -type f -iname "*.hbc")
        map=$(find "dist/_expo/static/js/android" -type f -iname "*.map")
        echo "Android bundle: $bundle"
        echo "Android map: $map"
        echo "bundle=$bundle" >> $GITHUB_OUTPUT
        echo "map=$map" >> $GITHUB_OUTPUT

    - name: Upload Source Maps For Android to Bugsnag
      if: ${{ inputs.platform == 'android' || inputs.platform == 'all' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        code_bundle_id=${{ inputs.version }}-${{ inputs.environment }}
        if [ -n "${{ inputs.code-bundle-suffix }}" ]; then
          code_bundle_id="${code_bundle_id}-${{ inputs.code-bundle-suffix }}"
        fi
        echo "Code bundle id: $code_bundle_id"
        npx bugsnag-source-maps upload-react-native \
          --api-key ${{ inputs.api-key }} \
          --code-bundle-id $code_bundle_id \
          --platform android \
          --source-map ${{ steps.find-source-maps-android.outputs.map }} \
          --bundle ${{ steps.find-source-maps-android.outputs.bundle }}
