name: Update GitHub Deployment Status (GitHub)
description: Update status for an existing GitHub Deployment
inputs:
  deployment-id:
    description: ID of the deployment
    required: true
  state:
    description: Deployment state (success, failure, inactive, error, queued, in_progress, pending)
    required: true
  description:
    description: Status description
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Update Deployment Status
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: Number(`${{ inputs.deployment-id }}`),
            state: `${{ inputs.state }}`,
            description: `${{ inputs.description }}`
          });
