name: Create Release Tag and Update Production Tag (GitHub)
description: Create a timestamped release tag and move/create the production tag to a given SHA
inputs:
  sha:
    description: Commit SHA to tag
    required: true
runs:
  using: composite
  steps:
    - name: Create a Release Tag and Update the Production Tag
      uses: actions/github-script@v7
      with:
        retries: 3
        script: |
          const date = new Date();
          const tag = date.toISOString().replace(/[-:Z]/g, "").replace(/[T\.]/g, "-");
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/release-${tag}`,
            sha: `${{ inputs.sha }}`
          });
          try {
            await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/production"
            });
            await github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/production",
              sha: `${{ inputs.sha }}`,
              force: true
            });
          } catch (error) {
            if (error.status === 404) {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/production",
                sha: `${{ inputs.sha }}`
              });
            } else {
              throw error;
            }
          }
