name: Notify Buddy
description: Sends a notification to Buddy

inputs:
  buddy-trigger-url:
    description: The Buddy trigger URL
    required: true
  deploy-serverless:
    description: Whether to deploy the serverless function
    required: true
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: FigurePOS/github-actions/.github/actions/buddy-notify-deploy-service@v2
      with:
        deploy-serverless: ${{ inputs.deploy-serverless }}
        service-name: ${{ inputs.service-name }}
        trigger-url: ${{ inputs.buddy-trigger-url }}

    - name: Send Slack Notification About Failure
      if: failure() && github.ref == 'refs/heads/master'
      uses: FigurePOS/github-actions/.github/actions/buddy-notify-fail-service@v2
      with:
        job-name: notify-buddy
        service-name: ${{ inputs.service-name }}
        trigger-url: ${{ inputs.buddy-trigger-url }}

