name: Notify Buddy
description: Sends a notification to Buddy

inputs:
  buddy-trigger-url:
    description: The Buddy trigger URL
    required: true
  service-name:
    description: The service name
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: FigurePOS/github-actions/.github/actions/buddy-notify-deploy-service@v5
      with:
        service-name: ${{ inputs.service-name }}
        trigger-url: ${{ inputs.buddy-trigger-url }}
