name: Notify Buddy about backend deployment
description: Sends a notification about backend deployment through Buddy to Slack

inputs:
  app-name:
    description: "Name of the app"
    required: true
  app-version:
    description: "Version of the app"
    required: true
  author:
    description: "Author of the build"
    required: false
  build-type:
    description: "Type of the build"
    required: true
    # options: over-the-air, native
  build-url:
    description: "URL of the build"
    required: false
  commit-hash:
    description: "Commit hash of the build"
    required: false
  commit-message:
    description: "Commit message of the build"
    required: true
  environment:
    description: "Environment of the app"
    required: true
    # options: development, production
  platform:
    description: "Platform of the app"
    required: true
    # options: ios, android, all
  trigger-url:
    description: "URL to trigger the notification"
    required: true

runs:
  using: composite
  steps:
    - name: Send notification
      shell: bash
      run: |
        echo "Sending notification to Buddy..."
        payload=$(jq -n \
          --arg appName "${{ inputs.app-name }}" \
          --arg appVersion "${{ inputs.app-version }}" \
          --arg environment "${{ inputs.environment }}" \
          --arg platform "${{ inputs.platform }}" \
          --arg commitMessage "${{ inputs.commit-message }}" \
          --arg buildType "${{ inputs.build-type }}" \
          --arg buildUrl "${{ inputs.build-url }}" \
          --arg commitHash "${{ inputs.commit-hash }}" \
          --arg author "${{ inputs.author }}" \
          '{"type": "dev-deployed", "mobile": true, "app_name": $appName, "app_version": $appVersion, "env": $environment, "platform": $platform, "commit_message": $commitMessage, "build_type": $buildType, "build_url": $buildUrl, "commit_hash": $commitHash, "author": $author}')
        echo "  payload: $payload"
        echo "  trigger-url: ${{ inputs.trigger-url }}"
        
        curl \
          -X POST \
          -H "Content-type: application/json" \
          --data "$payload" \
          ${{ inputs.trigger-url }}
        echo "Notification was sent to Slack"
