name: Push Docker image
description: Pushes a Docker image to ECR

inputs:
  aws-account-id:
    required: false
    default: 637192944017 # Root account
  aws-region:
    required: false
    default: us-east-1
  repository-name:
    required: true
  repository-url:
    required: false
    default: 637192944017.dkr.ecr.us-east-1.amazonaws.com
  service-name:
    required: true

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.service-name }}__oidc
        role-skip-session-tagging: true
    
    - id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - id: sha_short
      shell: bash
      run: echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

    - run: docker push "${{ inputs.repository-url }}/${{ inputs.repository-name }}:${{ steps.sha_short.outputs.sha_short }}"
      shell: bash
