name: Terraform Plan

inputs:
  aws-account-id:
    required: true
  aws-region:
    required: false
    default: us-east-1
  dir:
    required: false
    default: tf
  env:
    required: true
  service-name:
    required: true

runs:
  using: composite
  steps:
  - id: sha_short
    run: echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
    shell: bash
      
  - run: |-
      cd "${{ inputs.dir }}" || exit

      if terraform plan -detailed-exitcode --out tfplan.binary;
      then
          rm -rf tfplan.binary
          echo "No changes detected."
          echo -n "No changes detected." > plan.txt
          COMMENT_TPL=$(cat <<EOF
      Output from **${{ inputs.env }}** \`terraform plan\`:
      \`\`\`
      {{.}}
      \`\`\`
      EOF
      )
      else
          if [ $? -eq 1 ]
          then
              echo "Error running terraform plan"
              exit 1
          fi
          terraform show -no-color tfplan.binary > plan.txt

          COMMENT_TPL=$(cat <<EOF
      Output from **${{ inputs.env }}** \`terraform plan\`:

      <details>

      <summary>$(grep "Plan: " plan.txt)</summary>

      \`\`\`
      {{.}}
      \`\`\`

      </details>
      EOF
      )
      fi

      if [ "$(stat -c%s plan.txt)" -gt 50000 ]; then
          echo "The plan is too large, truncating..."
          head -c 50000 plan.txt > plan.txt.tmp
          mv plan.txt.tmp plan.txt
      fi

      export PR_NUMBER=${{ github.event.pull_request.number }}
      if [ -z "$PR_NUMBER" ]; then echo "Not a pull request - aborting"; exit 0; fi
      
      REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
      REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
      github-commenter \
          -owner "${REPO_OWNER}" \
          -repo "${REPO_NAME}" \
          -number "$PR_NUMBER" \
          -edit-comment-regex "Output from \*\*${{ inputs.env }}\*\* \`terraform plan\`" \
          -type pr \
          -template "$COMMENT_TPL" < plan.txt
      
    env:
      TF_VAR_aws_account_id: "${{ inputs.aws-account-id }}"
      TF_VAR_aws_region: "${{ inputs.aws-region }}"
      TF_VAR_deployment_tag: "${{ steps.sha_short.outputs.sha_short }}"
      TF_VAR_env: "${{ inputs.env }}"
      TF_VAR_git_commit_hash: "${{ github.sha }}"
      TF_VAR_service_name: "${{ inputs.service-name }}"
    shell: bash
