name: Terraform Plan

inputs:
  aws-account-id:
    required: true
  aws-region:
    required: false
    default: us-east-1
  dir:
    required: false
    default: tf
  env:
    required: true
  service-name:
    required: true

runs:
  using: composite
  steps:
  - id: sha_short
    shell: bash
    run: echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
    
  - id: plan
    shell: bash
    working-directory: ${{ inputs.dir }}
    run: |-
      trap 'exit_code="$?"; echo "exit_code=$exit_code"; echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"; if [[ "$exit_code" == "2" ]]; then exit 0; fi' EXIT
      # Capture both stdout and stderr to tf.console.txt, ensuring errors are visible
      tofu plan -detailed-exitcode -out=tf.plan -lock=false -no-color 2>&1 | tee tf.console.txt
    env:
      TF_VAR_aws_account_id: "${{ inputs.aws-account-id }}"
      TF_VAR_aws_region: "${{ inputs.aws-region }}"
      TF_VAR_deployment_tag: "${{ steps.sha_short.outputs.sha_short }}"
      TF_VAR_env: "${{ inputs.env }}"
      TF_VAR_git_commit_hash: "${{ github.sha }}"
      TF_VAR_service_name: "${{ inputs.service-name }}"
  - if: failure()
    shell: bash
    working-directory: ${{ inputs.dir }}
    run: |
      echo "::error::OpenTofu plan failed"
      if [ -f tf.console.txt ]; then
        echo "::group::OpenTofu Plan Output"
        cat tf.console.txt
        echo "::endgroup::"
        # Also output the last 50 lines to make errors more visible
        echo "::group::Last 50 lines of output"
        tail -n 50 tf.console.txt
        echo "::endgroup::"
      else
        echo "::error::tf.console.txt was not created - this indicates a severe error"
      fi

  - id: show
    if: steps.plan.outputs.exit_code != '1'
    shell: bash
    working-directory: ${{ inputs.dir }}
    run: |
      if [ -f tf.plan ]; then
        tofu show tf.plan -no-color > tf.show.txt

        # Diff of changes.
        # Filter lines starting with "  # " and save to tf.diff.txt, then prepend diff-specific symbols based on specific keywords.
        grep -E '^  # ' tf.show.txt | sed -e 's/^  # \(.* be created\)/+ \1/' -e 's/^  # \(.* be destroyed\)/- \1/' -e 's/^  # \(.* be updated\|.* be replaced\)/! \1/' -e 's/^  # \(.* be read\)/~ \1/' -e 's/^  # \(.*\)/# \1/' > tf.diff.txt || true
      else
        echo "::warning::tf.plan file not found, skipping show step"
      fi

  - id: post
    if: always()
    shell: bash
    working-directory: ${{ inputs.dir }}
    env:
      GH_TOKEN: ${{ github.token }}
    run: |
      # Check if plan was successful or failed
      if [[ "${{ steps.plan.outputs.exit_code }}" == "1" ]]; then
        # Plan failed
        summary="Error: OpenTofu plan failed"
        if [[ -f tf.console.txt ]]; then
          # Full log for the details section
          console=$(head -c 42000 tf.console.txt | sed '${/^  /d}')
          
          # Extract errors for the main comment
          errors=$(sed -n '/Error:/,$p' tf.console.txt)
          if [[ -n "$errors" ]]; then
            error_details=$(echo "$errors" | head -c 24000)
          else
            error_details="Could not parse errors from the plan output."
          fi
          
          diff="
          ${summary}
          
        \`\`\`
        ${error_details}
        \`\`\`
        "
        else
          console="Error: OpenTofu plan failed but no output was captured"
          diff="
          ${summary}
          
        \`\`\`
        No output was captured.
        \`\`\`
        "
        fi
      else
        # Plan was successful or had changes - use normal processing
        if [[ -f tf.show.txt ]]; then
          # Parse the tf.show.txt file (detailed output from tofu show), truncated for character limit.
          # Fix: Use temp file to avoid broken pipe with head
          grep -v '\.\.\.$' tf.show.txt > tf.temp.txt
          console=$(head -c 42000 tf.temp.txt | sed '${/^  /d}')
        else
          console="No plan output available"
        fi

        # Parse the tf.console.txt file (original plan output) for the summary.
        summary=$(tac tf.console.txt 2>/dev/null | grep -m 1 -E '^(Error:|Plan:|Apply complete!|No changes.|Success)' | tac 2>/dev/null || echo "No changes.")

        # If tf.diff.txt exists, display it within a diff block, truncated for character limit.
        if [[ -s tf.diff.txt ]]; then
          diff="
          ${summary}
          
        \`\`\`diff
        $(head -c 24000 tf.diff.txt)
        \`\`\`
        "
        else
          diff="
          \`\`\`diff
          No changes.
          \`\`\`
          "
        fi
      fi

      # Set outputs for both success and failure cases
      { echo 'result<<EOTFVIAPR'
        echo "$console"
        echo EOTFVIAPR
      } >> "$GITHUB_OUTPUT"
      
      { echo 'summary<<EOTFVIAPR'
        echo "$summary"
        echo EOTFVIAPR
      } >> "$GITHUB_OUTPUT"

      if [[ -s tf.diff.txt ]]; then
        { echo 'diff<<EOTFVIAPR'
          head -c 24000 tf.diff.txt
          echo EOTFVIAPR
        } >> "$GITHUB_OUTPUT"
      fi

      body=$(cat <<EOTFVIAPR
      ### terraform plan for \`${{ inputs.env }}\`
      
      ${diff}
      <details><summary>Detailed Plan</br>

      </summary>

      \`\`\`hcl
      ${console}
      \`\`\`
      </details>
      <!-- pr-${{ github.event.pull_request.number }}-${{ inputs.env }} -->
      EOTFVIAPR
      )

      # Post output to job summary.
      echo "$body" >> $GITHUB_STEP_SUMMARY
      
      # Post PR comment per update and if the PR number is not 0.
      # Check if the PR contains a bot comment with the same identifier.
      if [[ "${{ github.event.pull_request.number }}" != "" && "${{ github.event.pull_request.number }}" != "0" ]]; then
        list_comments=$(gh api /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments --method GET --field per_page=100)
        bot_comment=$(echo "$list_comments" | jq -r --arg identifier "pr-${{ github.event.pull_request.number }}-${{ inputs.env }}" '.[] | select(.user.type == "Bot") | select(.body | contains($identifier)) | .id' | head -n 1)
        
        if [[ -n "$bot_comment" ]]; then
          # Update existing comment.
          pr_comment=$(gh api /repos/${{ github.repository }}/issues/comments/${bot_comment} --method PATCH --field "body=${body}")
          echo "comment_id=$(echo "$pr_comment" | jq -r '.id')" >> "$GITHUB_OUTPUT"
        else
          # Post new comment.
          pr_comment=$(gh api /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments --method POST --field "body=${body}")
          echo "comment_id=$(echo "$pr_comment" | jq -r '.id')" >> "$GITHUB_OUTPUT"
        fi
      fi

      # Clean up files.
      rm -f tf.console.txt tf.show.txt tf.diff.txt tf.temp.txt tf.plan

