name: Install Dependencies
description: Install dependencies using yarn

inputs:
  additional-cache-path:
    description: Additional path to cache
    required: false
    default: ""
  directory:
    description: Directory to install dependencies in
    required: false
    default: "."
  prod:
    description: Whether to install only prod dependencies
    required: false
    default: false
  
runs:
  using: composite
  steps:
    - name: Set GitHub Packages Token
      shell: bash
      run: |
        yarn config set npmRegistries --json '{"https://npm.pkg.github.com":{"npmAlwaysAuth":true,"npmAuthToken": "${{ github.token }}"}}'

    - name: Setup Node Cache
      id: node-cache
      uses: useblacksmith/cache@v5
      with:
        path: |
          ${{ inputs.directory }}/node_modules
          ${{ inputs.additional-cache-path }}
        key: yarn-${{ runner.os }}-${{ inputs.prod == 'true' && 'prod' || 'dev' }}-${{ inputs.directory == '' && '.' || inputs.directory }}-${{ hashFiles(inputs.directory == '' && 'yarn.lock' || format('{0}/yarn.lock', inputs.directory)) }}

    - name: Install Dependencies
      shell: bash
      run: |
        if [ "${{ inputs.directory }}" != "" ]; then
          cd "${{ inputs.directory }}"
        fi
        yarn workspaces focus ${{ inputs.prod == 'true' && '--production' || '' }}
