name: Node License Compliance
description: Checks the license compliance of Node.js dependencies

inputs:
  allow:
    description: The licenses to allow
    required: false
    default: 0BSD;Apache-2.0;BSD-1-Clause;BSD-2-Clause;BSD-3-Clause;ISC;MIT;MIT-0;MPL-1.0;MPL-1.1;MPL-2.0;Python-2.0;Unlicense
  exclude:
    description: The pattern to exclude
    required: false
    default: /^@figure/

runs:
  using: 'composite'
  steps:
    - name: License Compliance Check
      run: |
        if ! [ -f "./node_modules/.bin/license-compliance" ]; then
          echo "Installing license-compliance..."
          npm install -D license-compliance
        fi
        ./node_modules/.bin/license-compliance --production --allow="${{ inputs.allow }}" --exclude="${{ inputs.exclude }}" --report=detailed
      shell: bash
