name: Node License Compliance
description: Checks the license compliance of Node.js dependencies

runs:
  using: 'composite'
  steps:
    - name: License compliance check
      uses: mikaelvesavuori/license-compliance-action@v1
      with:
        allow_licenses: 0BSD;Apache-2.0;BSD-1-Clause;BSD-2-Clause;BSD-3-Clause;ISC;MIT;MPL-1.0;MPL-1.1;MPL-2.0;Unlicense
        exclude_pattern: /^@figure/
