name: Setup Node
description: "Set up Node.js"

inputs:
  version:
    description: "Node.js version to use"
    default: "20.x"

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Set Up Node.js
      uses: useblacksmith/setup-node@v5
      with:
        node-version: ${{ inputs.version }}
        cache: "yarn"
      env:
        GITHUB_TOKEN: ${{ github.token }}
