name: Lambda Test
description: Runs tests for Lambda functions in a directory

inputs:
  directory:
    description: Directory containing Lambda functions
    required: false
    default: "./lambda"
  npm-legacy-peer-deps:
    description: Whether to use legacy peer dependencies
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Process Lambda Function
      shell: bash
      run: |
        if [ -f "${{ inputs.directory }}/package.json" ]; then
          cd "${{ inputs.directory }}"
          echo "Installing dependencies for ${{ inputs.directory }}"
          npm install --legacy-peer-deps=${{ inputs.npm-legacy-peer-deps }} || exit 1
          if grep -q "\"ci:test\":" package.json; then
            echo "Running tests for ${{ inputs.directory }}"
            if npm run ci:test 2>&1 | tee test-output.log; then
              # Test command succeeded
              if grep -q "No tests found" test-output.log; then
                echo "::warning::No tests found in Lambda function ${{ inputs.directory }}"
              fi
            else
              # Test command failed
              if grep -q "No tests found" test-output.log; then
                echo "::warning::No tests found in Lambda function ${{ inputs.directory }}"
              else
                echo "::error::Tests failed in Lambda function ${{ inputs.directory }}"
                exit 1
              fi
            fi
          else
            echo "::warning::Lambda function in ${{ inputs.directory }} does not have a ci:test script defined in package.json"
            echo "No ci:test script found in ${{ inputs.directory }}"
          fi
        else
          echo "::warning::No package.json found in ${{ inputs.directory }}"
        fi
