name: Lambda Test
description: Runs tests for Lambda functions in a directory

inputs:
  directory:
    description: Directory containing Lambda functions
    required: false
    default: "./lambda"
  npm-legacy-peer-deps:
    description: Whether to use legacy peer dependencies
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Process Lambda Functions
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        for dir in */; do
          if [ -f "${dir}package.json" ]; then
            echo "Processing Lambda function in ${dir}"
            (
              cd "${dir}" || exit 1
              echo "Installing dependencies for ${dir}"
              npm install --legacy-peer-deps=${{ inputs.npm-legacy-peer-deps }} || exit 1
              if grep -q "\"ci:test\":" package.json; then
                echo "Running tests for ${dir}"
                if npm run ci:test 2>&1 | tee test-output.log; then
                  # Test command succeeded
                  if grep -q "No tests found" test-output.log; then
                    echo "::warning::No tests found in Lambda function ${dir}"
                  fi
                else
                  # Test command failed
                  if grep -q "No tests found" test-output.log; then
                    echo "::warning::No tests found in Lambda function ${dir}"
                  else
                    echo "::error::Tests failed in Lambda function ${dir}"
                    exit 1
                  fi
                fi
              else
                echo "::warning::Lambda function in ${dir} does not have a ci:test script defined in package.json"
                echo "No ci:test script found in ${dir}"
              fi
            )
            if [ $? -ne 0 ]; then
              echo "::error::Failed to process Lambda function in ${dir}"
              exit 1
            fi
          fi
        done 
