name: "Fingerprint"
# This workflow is used to check the fingerprint of the mobile (expo) app and detect changes in the native layer during a PR.

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment"
        required: false
        type: string
        #options: development, production (we default to production, because we want to check primary the production fingerprint)
        default: "production"
      whitelabel:
        description: "Whitelabel (used for mobile ordering)"
        required: false
        type: string
        default: ""
      working-directory:
        description: "Working directory"
        required: false
        type: string
        default: "./"
      fingerprint-db-cache-key:
        description: A cache key to use for saving the fingerprint database (needed for monorepo so that each app has its own fingerprint database)
        required: false
        type: string
        default: fingerprint-db
      message-suffix:
        description: A suffix to add to the message
        required: false
        type: string
        default: ""
      comment-identifier:
        description: A identifier to use for the comment
        required: false
        type: string
        default: pr-fingerprint-check
    secrets:
      ENV_JSON:
        description: "Environment JSON"
        required: false

permissions:
  contents: read
  packages: read
  # REQUIRED: Allow comments of PRs
  pull-requests: write
  # REQUIRED: Allow updating fingerprint in action caches
  actions: write

jobs:
  fingerprint:
    name: "Check Expo Fingerprint"
    runs-on: ubuntu-latest
    env:
      APP_VARIANT: ${{ inputs.environment }}
      WHITELABEL: ${{ inputs.whitelabel }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # The ref has to be specified to make sure git checkout takes the real branch,
          # because for pull_request triggers, the action takes some temporary ref with weird name and message.
          ref: ${{ github.event.pull_request.head.ref }}
          # This makes sure that all commits are checked out, because the previous commit is needed for the fingerprint check.
          fetch-depth: 0

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: yarn

      - name: Set GitHub Packages Token
        shell: bash
        run: |
          npm config set @figurepos:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken ${{ github.token }}

      - name: Install dependencies
        run: yarn install

      - name: Set Environment
        uses: FigurePOS/github-actions/.github/actions/mobile-set-env@v3
        with:
          env-json: ${{ secrets.ENV_JSON }}
          destination: ${{ inputs.working-directory }}/env.json

      - name: Get Previous Git Commit
        uses: FigurePOS/github-actions/.github/actions/git-get-no-skip-ci-commit@v4
        id: get-previous-git-commit
        if: ${{ github.event_name == 'pull_request' }}
        with:
          start-git-ref: ${{ github.event.pull_request.base.sha }}

      - name: Check Fingerprint
        id: fingerprint
        uses: expo/expo-github-action/fingerprint@main
        with:
          working-directory: ${{ inputs.working-directory }}
          fingerprint-db-cache-key: ${{ inputs.fingerprint-db-cache-key }}
          previous-git-commit: ${{ steps.get-previous-git-commit.outputs.commit-sha }}

      - name: Print Fingerprint Diff
        env:
          JSON_DATA_VALUE: ${{ steps.fingerprint.outputs.fingerprint-diff }}
        run: |
          echo "Fingerprint diff:"
          echo "$JSON_DATA_VALUE" | jq '.'
          echo "Previous git commit: ${{ steps.get-previous-git-commit.outputs.commit-sha }}"n

      - name: Remove Comment
        uses: FigurePOS/github-actions/.github/actions/github-delete-comment@v4
        if: ${{ github.event_name == 'pull_request' && steps.fingerprint.outputs.fingerprint-diff == '[]' }}
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          identifier: ${{ inputs.comment-identifier }}

      - name: Add Comment
        uses: FigurePOS/github-actions/.github/actions/github-upsert-comment@v4
        if: ${{ github.event_name == 'pull_request' && steps.fingerprint.outputs.fingerprint-diff != '[]' }}
        env:
          GH_TOKEN: ${{ github.token }}
          JSON_DATA_VALUE: ${{ steps.fingerprint.outputs.fingerprint-diff }}
        with:
          identifier: ${{ inputs.comment-identifier }}
          body: |
            ## ⚠️ Native Changes Detected${{ inputs.message-suffix }}

            This PR contains changes that affect the native layer of the application. Please ensure you:

            1. Increment the native (minor) version number in `package.json`.

            2. After the PR is merged, make sure to start the builds on EAS.<br>
            For more information see `Releasing new minor (native) version` in our [documentation](https://twbrds.atlassian.net/wiki/spaces/PT/pages/164009/Building+Expo+Apps).

            <details>
            <summary>Changes Detected by Fingerprint</summary>

            ```json
            JSON_DATA_PLACEHOLDER
            ```

            </details>
