name: Production Deployment
on: 
  workflow_call:
    inputs:
      aws-account-id:
        description: AWS account ID
        required: false
        type: string
        default: "682919404744"
      aws-region:
        description: AWS region
        required: false
        type: string
        default: us-east-1
      db-tunnel-mapping:
        description: DB tunnel mapping
        required: false
        type: string
        default: ""
      service-name:
        description: Service name
        required: true
        type: string
      sha:
        description: Release commit SHA
        required: true
        type: string
    secrets:
      BUDDY_TRIGGER_URL:
        description: Buddy trigger URL
      GH_TOKEN_TERRAFORM:
        description: GitHub token to access other private repositories
        required: false

permissions:
  # Needed to checkout repository code, read repository contents and create tags
  contents: write
  # Required for OIDC authentication with AWS
  id-token: write
  # Allows reading from GitHub container registry (ghcr.io)
  packages: read
  # Allows creating and updating Deployments
  deployments: write

jobs:
  terraform-deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    env:
      AWS_REGION: ${{ inputs.aws-region }}
    steps:
      - name: Create Deployment
        id: create_deployment
        uses: ./.github/actions/github-deployment-create
        with:
          environment: production
          ref: ${{ inputs.sha }}
          description: Deploy
      - uses: FigurePOS/github-actions/.github/actions/ci-terraform-apply@v4
        with:
          aws-account-id: ${{ inputs.aws-account-id }}
          aws-region: ${{ inputs.aws-region }}
          buddy-trigger-url: ${{ secrets.BUDDY_TRIGGER_URL }}
          db-tunnel-mapping: ${{ inputs.db-tunnel-mapping }}
          env: production
          github-token-terraform: ${{ secrets.GH_TOKEN_TERRAFORM }}
          service-name: ${{ inputs.service-name }}
          sha: ${{ inputs.sha }}

      - name: Create a Release Tag and Update the Production Tag
        uses: ./.github/actions/github-tag-release
        with:
          sha: ${{ inputs.sha }}

      - name: Update Deployment Status - Success
        if: success()
        uses: ./.github/actions/github-deployment-status
        with:
          deployment-id: ${{ steps.create_deployment.outputs.deployment-id }}
          state: success
          description: Production deployment completed successfully

      - name: Update Deployment Status - Failure
        if: failure()
        uses: ./.github/actions/github-deployment-status
        with:
          deployment-id: ${{ steps.create_deployment.outputs.deployment-id }}
          state: failure
          description: Production deployment failed
