name: Get Expo App Name
description: Get the name of the App from EAS configuration
# This action requires EAS being set up. In some other task before.

inputs:
  environment:
    description: "Environment to get the app name for"
    required: true
  # This is needed because of the way the EAS CLI works
  # Provide any platform the app supports as input
  platform:
    description: "Platform to get the app name for"
    required: true
  whitelabel:
    description: "Whitelabel (used for mobile ordering)"
    required: false
    default: ""

outputs:
  app-name:
    description: "App name of the project"
    value: ${{ steps.parse.outputs.app-name }}

runs:
  using: composite
  steps:
    - name: Get EAS Config
      id: get-config
      env:
        APP_VARIANT: ${{ inputs.environment }}
        WHITELABEL: ${{ inputs.whitelabel }}
      run: |
        easConfig=$(eas config -e ${{ inputs.environment }} -p ${{ inputs.platform == 'all' && 'ios' || inputs.platform }} --non-interactive --json)
        echo "config=$(echo "$easConfig" | tr -d '\n')" >> $GITHUB_OUTPUT
        echo "EAS config:"
        echo $easConfig
      shell: bash
    - name: Get the app name
      id: parse
      shell: bash
      run: |
        echo 'app-name=${{ fromJson(steps.get-config.outputs.config).appConfig.name }}' >> $GITHUB_OUTPUT
